# Nome do workflow
name: Generate Changelog
# Evento que aciona o workflow
on:
  # Aciona quando há um push para a branch main
  push:
    branches:
      - main
# Definição dos jobs do workflow
jobs:
  # Job para gerar o changelog
  generate_changelog:
    # Sistema operacional onde o job será executado
    runs-on: ubuntu-latest
    # Permissões necessárias
    permissions:
      contents: write
    # Passos do job
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Gera o changelog
      - name: Generate Changelog
        id: generate_changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Define os tipos de commit e suas descrições
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            docs: Documentation
            style: Style Changes
            refactor: Code Refactoring
            perf: Performance Improvements
            test: Tests
            build: Build System
            ci: CI/CD
            chore: Chores
            revert: Reverts
          default-commit-type: Other Changes
          release-name: v0.1.0
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: true
          use-github-autolink: true

      # Verifica se o changelog foi gerado
      - name: Check Changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "Changelog was not generated"
            touch CHANGELOG.md
            echo "# Changelog" > CHANGELOG.md
          fi

      # Faz commit das mudanças
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update CHANGELOG.md"

      # Faz push das mudanças
      - name: Push changes
        run: git push
