# Nome do workflow
name: Security Scan

# Eventos que acionam o workflow
on:
  # Aciona quando há um push para a branch main
  push:
    branches: [ main ]
  # Aciona quando há um pull request para a branch main
  pull_request:
    branches: [ main ]
  # Aciona semanalmente (todo domingo à meia-noite)
  schedule:
    - cron: '0 0 * * 0'

# Definição dos jobs do workflow
jobs:
  # Job de varredura de segurança
  security-scan:
    # Sistema operacional onde o job será executado
    runs-on: ubuntu-latest
    # Passos do job
    steps:
    # Faz checkout do código
    - uses: actions/checkout@v4
    # Configura o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    # Instala as dependências necessárias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    # Executa a ferramenta Bandit para análise de segurança
    - name: Run Bandit
      run: |
        bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}"
